---
  - src: git@github.com:kostidan/mnt-homeworks-ansible.git
    scm: git
    version: "main"
    name: elastic_role
  - src: git@github.com:kostidan/kibana-role.git
    scm: git
    version: "main"
    name: kibana_role   
  - src: git@github.com:kostidan/filebeat-role.git
    scm: git
    version: "main"
    name: filebeat_role        